services:
  spark:
    image: apache/spark:3.5.1
    container_name: spark-container
    volumes:
      - ../:/app
    working_dir: /app
    command: tail -f /dev/null

  postgres:
    image: postgres:15
    container_name: etl-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow-container
    depends_on:
      - postgres
      - spark
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ../dags:/opt/airflow/dags
      - ../:/app
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
      airflow standalone
      "